### ISSUE TITLE
Unable to decode Core ML Document

### ISSUE THREAD

**Issue by gigisommo** [sgl0v/ImageColorizer#1]
Hi @sgl0v,

this looks very cool!
I cloned the repo to try it out, but the CoreML model is not working.
I get this error when I select it. I tried on both Xcode 12.4 and 12.5.

![Image 14-05-2021 at 15 27](https://user-images.githubusercontent.com/2893584/118285193-1ba29c80-b4c9-11eb-88a7-fa652bfc899a.jpg)

Thank you

**Comment by andreyoshev** [comment]
Same

**Comment by alxrguz** [comment]
Good afternoon, I ran into the same problem, did you manage to solve it? I'd like to try this functionality out, thanks in advance

**Comment by sgl0v** [comment]
The model is stored in [git-lfs](https://github.com/git-lfs/git-lfs). It could be that one is not fetched automatically for some reason. Could you please check the `coremlColorizer.ml` file size(should be 136,2 MB) run `git lfs fetch`?

**Comment by gigisommo** [comment]
Thank you, it worked! And it is a very cool project!
